name: Dart


on: [push, pull_request]

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.x"
          architecture: x64
          
      - name: Analyze project source
        run: flutter analyze --disable-telemetry
  
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    needs: analyse
    
    steps: 
      - name: Clone Flutter repository with version 3.10.x
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.x"
          architecture: x64 
      - run: flutter doctor -v --disable-telemetry

      - uses: actions/checkout@v3 
      
      - name: Get packages
        run: flutter pub get

      - name: Run tests
        run: flutter test
