name: Test

on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: macos-latest
   
    steps: 
      - uses: actions/checkout@v3 
      
      - name: Clone Flutter repository with version 3.10.x
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.x"
          architecture: x64
          cache: true
      - run: flutter doctor -v --disable-telemetry
      
      - name: Get pub packages
        run: flutter pub get
        
      - run: flutter analyze
      
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
      
      - name: Run unit-tests
        run: flutter test --exclude-tags golden 

      - name: Run golden tests
        run: flutter test --tags=golden --dart-define=CI=true